apiVersion: v1
kind: ReplicationController
metadata:
  name: production-controller
spec:
  replicas: 2
  selector:
    app: production
  template:
    metadata:
      name: production
      labels:
        app: production
    spec:
      containers:
      - name: production
        image: stephanstu/predictor
        ports:
        - containerPort: 80
