Description:
  This script deploys the infrastructure needed for the continuous integration / continuous deployment pipline utilizing AWS' container services.
Parameters:
  RepositoryName:
    Description: A name for the container repository in AWS' ECR.
    Type: String
  UdacityCapstoneDeveloperIP:
    Description: IP of the Cloud DevOps Engineer in CIDR-Notation
    Type: String
    Default: 02.006.004.116/32
Resources:
  UdacityCapstoneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow connections from specified CIDR ranges, i.e. my Mac to e.g. configure Jenkins
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 8000
        ToPort: 8080
        CidrIp: !Ref UdacityCapstoneDeveloperIP
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref UdacityCapstoneDeveloperIP
  UdacityCapstoneServer:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroups:
      - !Ref UdacityCapstoneSecurityGroup
      ImageId: ami-0e342d72b12109f91
      InstanceType: c3.large
      # Enter the name of your Key-Pair here:
      KeyName: UdacityCapstoneKeyPair
Outputs:
  UdacityCapstoneJenkinsServerURL:
    Description: The URL where you can access Jenkins (after it is setup!)
    Value: !Join [ "", [ "http://", !GetAtt UdacityCapstoneServer.PublicDnsName, ":8080" ] ]
    Export:
      Name: UdacityCapstoneServerURL
